### ISSUE TITLE
PocketBase 404 Error: "Missing collection context" on /fetchGuilds

### ISSUE THREAD

**Issue by victornavorskie** [cially/cially#39]
When accessing the Cially dashboard, the frontend loads but fails to display any guilds. The console logs show the following error:

![Image](https://github.com/user-attachments/assets/86b26053-a389-4924-9465-797300feff08)

```
[ERROR] Failed to communicate with the PocketBase Instance. /fetchGuilds
ClientResponseError 404: Missing collection context.
    at /app/node_modules/.pnpm/pocketbase@0.25.2/node_modules/pocketbase/dist/pocketbase.cjs.js:1:37046
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchGuilds (/app/http/API/functions/fetchGuilds.js:16:18) {
  url: 'http://pocketbase:8090/api/collections/guilds/records?page=1&perPage=500&skipTotal=1',
  status: 404,
  response: { data: {}, message: 'Missing collection context.', status: 404 },
  isAbort: false,
  originalError: {
    url: 'http://pocketbase:8090/api/collections/guilds/records?page=1&perPage=500&skipTotal=1',
    status: 404,
    data: { data: {}, message: 'Missing collection context.', status: 404 }
  }
}
```

Steps to reproduce

    Deploy the stack with the provided Docker Compose file (below).

    Visit the web UI through Traefik at https://cially.home.exam.com.

    The dashboard UI loads, but no guilds are shown.

    Error appears in logs related to /fetchGuilds.

```
services:
  cially-bot:
    image: ghcr.io/skellgreco/cially-bot:latest
    container_name: cially-bot
    restart: unless-stopped
    # env_file:
    #   - .env
    environment:
      - TOKEN=TOKEN
      - CLIENT_ID=CLIENT_ID
      - API_URL=http://cially-bot:3001
      - DEBUGGING=${BOT_DEBUGGING:-FALSE}
      - POCKETBASE_URL=http://pocketbase:8090
      - GUILD_COLLECTION=guilds
      - MESSAGE_COLLECTION=messages
      - INVITE_COLLECTION=invites
      - MEMBER_LEAVES_COLLECTION=member_leaves
      - MEMBER_JOINS_COLLECTION=member_joins
      - PORT=3001
    # ports:
    #   - "3001:3001"
    depends_on:
      - pocketbase
      - cially-web
    networks:
      - backend

  cially-web:
    image: ghcr.io/skellgreco/cially-web:latest
    container_name: cially-web
    restart: unless-stopped
    environment:
      # Runtime environment variables
      - NEXT_PUBLIC_BOT_API_URL=http://cially-bot:3001
      - POCKETBASE_URL=http://pocketbase:8090
      - MESSAGE_COLLECTION=messages
      - INVITE_COLLECTION=invites
      - MEMBER_LEAVES_COLLECTION=member_leaves
      - MEMBER_JOINS_COLLECTION=member_joins
      - GUILDS_COLLECTION=guilds
    # ports:
    #   - "3000:3000"
    depends_on:
      - pocketbase
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cially-web.rule=Host(`cially.home.exam.com`)"
      - "traefik.http.routers.cially-web.tls=true"
      - "traefik.http.routers.cially-web.entrypoints=https"
      - "traefik.http.services.cially-web.loadbalancer.server.port=3000"
    networks:
      - proxy
      - backend

  pocketbase:
    image: ghcr.io/keksiqc/pocketbase:0.26.6
    container_name: cially-pocketbase
    restart: unless-stopped
    volumes:
      - pocketbase-data:/pb/pb_data
    # ports:
    #   - "8090:8090"
    networks:
      - backend

networks:
  proxy:
    external: true
  backend:
    external: true

volumes:
  pocketbase-data:
```
